[package]
name = "denatural"
version = "0.0.0"
authors = ["ly3xqhl8g9 <ly3xqhl8g9@plurid.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "denatural_library"
path = "source/library/lib.rs"

[[bin]]
name = "denatural_binary"
path = "source/binary/main.rs"

[dependencies]
